# Generated by Django 5.0.4 on 2024-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], default='reserved', max_length=8),
        ),
    ]
