# Generated by Django 5.0.4 on 2024-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='reserved', max_length=10),
        ),
    ]
