# Generated by Django 5.0.4 on 2024-05-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_borrowlist_status_borrowrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowlist',
            name='status',
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_list', to='book.book'),
        ),
        migrations.AlterField(
            model_name='borrowlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
